// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyIMS.Data;

#nullable disable

namespace PharmacyIMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922072933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyIMS.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "مسكنات وخافضات حرارة",
                            Description = "أدوية تسكين الألم وخفض الحرارة"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "مضادات حيوية",
                            Description = "أدوية علاج الالتهابات البكتيرية"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "فيتامينات ومكملات غذائية",
                            Description = "فيتامينات ومعادن ومكملات صحية"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "أدوات ومستلزمات طبية",
                            Description = "أدوات طبية ومستهلكات صيدلية"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "مستحضرات العناية الشخصية",
                            Description = "منتجات العناية بالبشرة والعناية الشخصية"
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            DosageForm = "أقراص",
                            ExpiryDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowStockThreshold = 30,
                            Manufacturer = "النصر للأدوية",
                            ProductName = "باراسيتامول 500 مجم",
                            SKU = "MED-1001",
                            StockQuantity = 150,
                            UnitPrice = 12.50m
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            DosageForm = "أقراص",
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowStockThreshold = 20,
                            Manufacturer = "النصر للأدوية",
                            ProductName = "إيبوبروفين 400 مجم",
                            SKU = "MED-1002",
                            StockQuantity = 8,
                            UnitPrice = 18.00m
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 2,
                            DosageForm = "كبسولات",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowStockThreshold = 15,
                            Manufacturer = "المتحدة للأدوية",
                            ProductName = "أموكسيسيلين 500 مجم",
                            SKU = "MED-2001",
                            StockQuantity = 5,
                            UnitPrice = 35.75m
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 2,
                            DosageForm = "أقراص",
                            ExpiryDate = new DateTime(2027, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowStockThreshold = 15,
                            Manufacturer = "المتحدة للأدوية",
                            ProductName = "أزيثروميسين 250 مجم",
                            SKU = "MED-2002",
                            StockQuantity = 60,
                            UnitPrice = 42.00m
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 3,
                            DosageForm = "أقراص فوارة",
                            ExpiryDate = new DateTime(2027, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowStockThreshold = 20,
                            Manufacturer = "شركة الحياة",
                            ProductName = "فيتامين سي 1000 مجم فوار",
                            SKU = "VIT-3001",
                            StockQuantity = 90,
                            UnitPrice = 55.00m
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 3,
                            DosageForm = "كبسولات",
                            ExpiryDate = new DateTime(2027, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowStockThreshold = 15,
                            Manufacturer = "شركة الحياة",
                            ProductName = "زنك + فيتامين د3",
                            SKU = "VIT-3002",
                            StockQuantity = 12,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 4,
                            DosageForm = "جهاز",
                            LowStockThreshold = 5,
                            Manufacturer = "المتحدة للمستلزمات",
                            ProductName = "جهاز قياس ضغط الدم الرقمي",
                            SKU = "DEV-4001",
                            StockQuantity = 10,
                            UnitPrice = 450.00m
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 4,
                            DosageForm = "علبة",
                            LowStockThreshold = 40,
                            Manufacturer = "المتحدة للمستلزمات",
                            ProductName = "كمامات طبية (علبة 50)",
                            SKU = "DEV-4002",
                            StockQuantity = 200,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 5,
                            DosageForm = "كريم",
                            ExpiryDate = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowStockThreshold = 10,
                            Manufacturer = "شركة الحياة",
                            ProductName = "كريم مرطب للبشرة الجافة",
                            SKU = "CARE-5001",
                            StockQuantity = 3,
                            UnitPrice = 85.00m
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseID"));

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseItem", b =>
                {
                    b.Property<int>("PurchaseItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseItemID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("PurchaseID");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Sale", b =>
                {
                    b.Property<int>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleID"));

                    b.Property<string>("CustomerInfo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleItem", b =>
                {
                    b.Property<int>("SaleItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleItemID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SaleID");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            Address = "القاهرة - المنطقة الصناعية",
                            ContactName = "أحمد فتحي",
                            Email = "sales@nasr-pharma.com",
                            Phone = "01001234567",
                            SupplierName = "شركة النصر للأدوية"
                        },
                        new
                        {
                            SupplierID = 2,
                            Address = "الجيزة - 6 أكتوبر",
                            ContactName = "منى عبد الله",
                            Email = "info@united-med.com",
                            Phone = "01112345678",
                            SupplierName = "المتحدة للمستلزمات الطبية"
                        },
                        new
                        {
                            SupplierID = 3,
                            Address = "الإسكندرية - سموحة",
                            ContactName = "كريم صلاح",
                            Email = "contact@hayah-vit.com",
                            Phone = "01223456789",
                            SupplierName = "شركة الحياة للفيتامينات"
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.SupplierProduct", b =>
                {
                    b.Property<int>("SupplierProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierProductID"));

                    b.Property<decimal>("ContractPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierSKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SupplierProductID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SupplierID");

                    b.ToTable("SupplierProducts");

                    b.HasData(
                        new
                        {
                            SupplierProductID = 1,
                            ContractPrice = 9.50m,
                            LeadTimeDays = 3,
                            ProductID = 1,
                            SupplierID = 1,
                            SupplierSKU = "NSR-P500"
                        },
                        new
                        {
                            SupplierProductID = 2,
                            ContractPrice = 14.00m,
                            LeadTimeDays = 3,
                            ProductID = 2,
                            SupplierID = 1,
                            SupplierSKU = "NSR-I400"
                        },
                        new
                        {
                            SupplierProductID = 3,
                            ContractPrice = 28.00m,
                            LeadTimeDays = 5,
                            ProductID = 3,
                            SupplierID = 2,
                            SupplierSKU = "UM-AMX500"
                        },
                        new
                        {
                            SupplierProductID = 4,
                            ContractPrice = 33.00m,
                            LeadTimeDays = 5,
                            ProductID = 4,
                            SupplierID = 2,
                            SupplierSKU = "UM-AZI250"
                        },
                        new
                        {
                            SupplierProductID = 5,
                            ContractPrice = 42.00m,
                            LeadTimeDays = 2,
                            ProductID = 5,
                            SupplierID = 3,
                            SupplierSKU = "HY-VITC1000"
                        },
                        new
                        {
                            SupplierProductID = 6,
                            ContractPrice = 50.00m,
                            LeadTimeDays = 2,
                            ProductID = 6,
                            SupplierID = 3,
                            SupplierSKU = "HY-ZND3"
                        },
                        new
                        {
                            SupplierProductID = 7,
                            ContractPrice = 380.00m,
                            LeadTimeDays = 7,
                            ProductID = 7,
                            SupplierID = 2,
                            SupplierSKU = "UM-BPM01"
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.Product", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Purchase", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseItem", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Product", "Product")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleItem", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SupplierProduct", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Product", "Product")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.Supplier", "Supplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Product", b =>
                {
                    b.Navigation("PurchaseItems");

                    b.Navigation("SaleItems");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Supplier", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("SupplierProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
